title: Felipe Monteiro # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

<div style="max-height: 400px; overflow-y: auto;">
  <ul>
   <li>
      <a href="https://www.linkedin.com/in/monteiroflp/">
        <i class="fab fa-linkedin" style="color: blue;"></i> LinkedIn Profile
      </a>
    </li>
    <li>
      <a href="https://github.com/felpsmonteiro">
        <i class="fab fa-github"></i> GitHub Profile
      </a>
    </li>
    <li>MSc in Computer Science.</li>
    <li>+6 years of experience working closely with business stakeholders to comprehend information needs and establish project deliverables.</li>
    <li>+3 years working as a Data Analyst supporting business operations through Data-Driven insights.</li>
    <li>+4 years translating business requirements into needs.</li>
    <li>Proficient in Excel, PowerQuery, PowerBI, SQL, and Python.</li>
    <li>Skilled in SQL, Data Extraction, Web Scraping, Tableau, Snowflake, Alteryx, Looker, Data Analysis, MS Power Automation, Jira, Confluence, AWS, GCP, and Git.</li>
  </ul>
</div>

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
